FROM openjdk:17-bullseye AS builder

RUN apt-get update && \
    apt-get install -y build-essential maven tree

COPY src ./src
COPY pom.xml .
RUN mvn -B clean package spring-boot:repackage
RUN tree

FROM python:3.9.10-slim-bullseye

RUN apt-get update && \
    apt-get install -y openjdk-17-jre figlet netcat telnet tree

RUN mkdir -p /cloudacademy/app
WORKDIR /cloudacademy/app
RUN ls -la

COPY --from=builder target/backend-*.jar ./backend.jar

EXPOSE 8080

CMD ["java", "-jar", "backend.jar"]
